/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiComponentsRouteImport } from './routes/ui-components'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ContractReviewPreviewRouteImport } from './routes/contract-review-preview'
import { Route as ChatPreviewRouteImport } from './routes/chat-preview'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'

const UiComponentsRoute = UiComponentsRouteImport.update({
  id: '/ui-components',
  path: '/ui-components',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractReviewPreviewRoute = ContractReviewPreviewRouteImport.update({
  id: '/contract-review-preview',
  path: '/contract-review-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatPreviewRoute = ChatPreviewRouteImport.update({
  id: '/chat-preview',
  path: '/chat-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat-preview': typeof ChatPreviewRoute
  '/contract-review-preview': typeof ContractReviewPreviewRoute
  '/sign-in': typeof SignInRoute
  '/ui-components': typeof UiComponentsRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat-preview': typeof ChatPreviewRoute
  '/contract-review-preview': typeof ContractReviewPreviewRoute
  '/sign-in': typeof SignInRoute
  '/ui-components': typeof UiComponentsRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRoute
  '/chat-preview': typeof ChatPreviewRoute
  '/contract-review-preview': typeof ContractReviewPreviewRoute
  '/sign-in': typeof SignInRoute
  '/ui-components': typeof UiComponentsRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat-preview'
    | '/contract-review-preview'
    | '/sign-in'
    | '/ui-components'
    | '/demo/storybook'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat-preview'
    | '/contract-review-preview'
    | '/sign-in'
    | '/ui-components'
    | '/demo/storybook'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/chat-preview'
    | '/contract-review-preview'
    | '/sign-in'
    | '/ui-components'
    | '/demo/storybook'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRoute
  ChatPreviewRoute: typeof ChatPreviewRoute
  ContractReviewPreviewRoute: typeof ContractReviewPreviewRoute
  SignInRoute: typeof SignInRoute
  UiComponentsRoute: typeof UiComponentsRoute
  DemoStorybookRoute: typeof DemoStorybookRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui-components': {
      id: '/ui-components'
      path: '/ui-components'
      fullPath: '/ui-components'
      preLoaderRoute: typeof UiComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract-review-preview': {
      id: '/contract-review-preview'
      path: '/contract-review-preview'
      fullPath: '/contract-review-preview'
      preLoaderRoute: typeof ContractReviewPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-preview': {
      id: '/chat-preview'
      path: '/chat-preview'
      fullPath: '/chat-preview'
      preLoaderRoute: typeof ChatPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRoute,
  ChatPreviewRoute: ChatPreviewRoute,
  ContractReviewPreviewRoute: ContractReviewPreviewRoute,
  SignInRoute: SignInRoute,
  UiComponentsRoute: UiComponentsRoute,
  DemoStorybookRoute: DemoStorybookRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
